install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - dotnet restore --configfile .nuget/NuGet.Config
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - ps: dotnet build

# after_build:
#   - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"

test_script:
  - ps: dotnet test --logger Appveyor tests/FileServer/FileServer.Tests.csproj